sonarqube-check:
  tags:
    - sonar-scanner-windows
  stage: sonar-test
  variables:
    SONAR_SOURCEENCODING: "UTF-8" 
    SONAR_PROJECTNAME: "MASA.IoT"
    SONAR_PROJECTKEY: "MASA-IOT_MASA.IoT_AYIka5IqMgcW0bQ3LsA_"
    SONAR_PROJECTVERSION: "1.0"
    SONAR_SOURCES: ". "
  script:
    - echo $SONAR_HOST_URL
    - ls
    - pwd 
    - sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.sourceEncoding=$SONAR_SOURCEENCODING -D sonar.projectName$SONAR_PROJECTNAME  -D sonar.projectVersion=$SONAR_PROJECTVERSION -D sonar.sources=.  -D sonar.login=$SONAR_LOGIN    -D sonar.projectKey=$SONAR_PROJECTKEY
  allow_failure: true
  only:
    - merge_requests
    - master
    - develop
