version: '3.4'

services:
  masa.tsc.database:
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
       - "1433:1433"
     environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y

  masa.tsc.service.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  masa.tsc.service.admin.dapr:
    image: "daprio/daprd:1.7.1"
    command: ["./daprd",
      "-app-id", "masa-tsc-service-admin",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    depends_on:
      - masa.tsc.service.admin
    volumes:
      - "./dapr/components/:/components"
    network_mode: "service:masa.tsc.service.admin"

  masa.tsc.ui.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - masa.tsc.service.admin

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"