rollout-prd-service-admin:
  stage: rollout-prd
  extends:
    - .values-service-admin-prd
    - .values-prd-public-service
    - .rollout
  only:
    refs:
      - main
    changes:
      - src/Services/Masa.Tsc.Service.Admin/**/*
      - .gitlab-ci.yml
  when: manual

rollout-prd-ui-admin:
  stage: rollout-prd
  extends:
    - .values-ui-admin-prd
    - .values-prd-public-ui
    - .rollout
  only:
    refs:
      - main
    changes:
      - src/Web/Masa.Tsc.Web.Admin.Server/**/*
      - .gitlab-ci.yml
  when: manual