rollout-staging-service-admin:
  stage: rollout-staging
  extends:
    - .values-service-admin-staging
    - .values-staging-public-service
    - .rollout
  only:
    refs:
      - main
    changes:
      - src/Services/Masa.Tsc.Service.Admin/**/*
      - .gitlab-ci.yml
  when: manual

rollout-staging-ui-admin:
  stage: rollout-staging
  extends:
    - .values-ui-admin-staging
    - .values-staging-public-ui
    - .rollout
  only:
    refs:
      - main
    changes:
      - src/Web/Masa.Tsc.Web.Admin.Server/**/*
      - .gitlab-ci.yml
  when: manual